on:
 push:
  branches:
   - main
 schedule:
  - cron: '38 01 * * *'
    timezone: 'Europe/Berlin'
 workflow_dispatch:

jobs:
 build:
  runs-on: ubuntu-latest

  container:
   image: archlinux:latest

  permissions:
   contents: write
   pages: write
   id-token: write

  steps:
   - name: Installing Dependencies
     run: |
      pacman --noconfirm -Syu \
      tree \
      git \
      devtools \
      debugedit \
      base-devel

   - name: Checkout
     uses: actions/checkout@v4

   - name: Check for new Version
     id: version
     run: |
      cd "$GITHUB_WORKSPACE/neovim"
      if [[ $(./newest_available_tag.sh) != $(./last_built_tag.sh) ]]; then
       echo "new_version=true" >> "$GITHUB_OUTPUT"
       ./newest_available_tag.sh
      else
       echo "new_version=false" >> "$GITHUB_OUTPUT"
      fi

   - name: Update PKGBUILD
     if: steps.version.outputs.new_version == 'true'
     run: |
      cd "$GITHUB_WORKSPACE/neovim"
      sed -i "s/^pkgver=.*/pkgver=$(./newest_available_tag.sh)/" PKGBUILD

   - name: Build Package
     if: steps.version.outputs.new_version == 'true'
     run: |
      cp -r "$GITHUB_WORKSPACE/neovim" /tmp/
      useradd -m builder
      echo 'builder ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/builder
      chmod 440 /etc/sudoers.d/builder
      chown -R builder:builder /tmp/neovim
      cd /tmp/neovim
      su builder -c 'makepkg -sf --noconfirm'
      rm neovim-debug*

   - name: Add to Repo
     if: steps.version.outputs.new_version == 'true'
     run: |
      cd "$GITHUB_WORKSPACE/repository/x86_64"
      if [[ -f "myrepo.db.tar.gz" ]]; then
       repo-remove myrepo.db.tar.gz neovim
      fi
      rm -f neovim-*.pkg.tar.zst

      cp /tmp/neovim/neovim-*.pkg.tar.zst .
      repo-add myrepo.db.tar.gz neovim-*.pkg.tar.zst
      ls

   - name: Update Repo
     if: steps.version.outputs.new_version == 'true'
     run: |
      cd "$GITHUB_WORKSPACE"
      git config --global --add safe.directory $GITHUB_WORKSPACE
      git config user.name "github-actions"
      git config user.email "a@a.com"
      git add "$GITHUB_WORKSPACE/neovim/PKGBUILD"
      git add "$GITHUB_WORKSPACE/repository/"
      git commit -m "Neovim version incremented"
      git push origin master

   - name: Setup Pages
     uses: actions/configure-pages@v5

   - name: Upload repository
     uses: actions/upload-pages-artifact@v4
     with:
      path: ./repository

   - name: Deploy to GitHub Pages
     id: deployment
     uses: actions/deploy-pages@v4
